name: 04-variable-precedence
on:
    workflow_dispatch:
env:
    APPLICATION_NAME: jasmika-app-workflow
jobs:
    dev-job:
        runs-on: ubuntu-latest
        env:
            APPLICATION_NAME: jasmika-app-job-level
        steps:
            - name: printing variables
              env:
                APPLICATION_NAME: jasmika-app-step-level
              run: |
               echo "Printing environmental variables "
               echo "Application name is $APPLICATION_NAME"

