name: 05-github-env
on:
    workflow_dispatch:
jobs: 
  github-env-variables:
    runs-on: ubuntu-latest
    steps:
        - name: Set variables 
          run: |
           echo "APP_VERSION=1.0.0" >>$GITHUB_ENV
           echo "NAME=Anki" >>$GITHUB_ENV
           echo "Trying to print APP_VERSION and NAME in the same step "
           echo "Application version is $APPLICATION_NAME"
           echo "Name is $NAME"
        - name: Print variables
          run: |
           echo "Trying to print APP_VERSION and NAME in the next step "
           echo "Application version is $APP_VERSION"
           echo "Name is $NAME"

# First Step : APP_VERSION and NAME print nothing 
#second step : APP_VERSION and NAME are printing correctly 
#$GITHUB_ENV is a special file that allows you to set environment variables that will be available to subsequent steps 
#$GITHUB_ENV variable are only available in the steps that come after the step where they are set 
#$GITHUB_ENV variable are only available in the same job 
